# Generated by Django 5.0b1 on 2023-11-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='Beginner'),
        ),
    ]
