# Generated by Django 4.2.6 on 2023-10-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0002_remove_student_instructor_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='students',
            field=models.ManyToManyField(blank=True, to='myappF23.student'),
        ),
    ]
