# Generated by Django 5.0b1 on 2023-11-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0003_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='interested',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
